[project]
name = "meshwar"
version = "1.0.0"
description = "Meshwar Egyptian transit app"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "flet>=0.26.0",
    "flet-map",
    "geopy",
    "plyer",
]

[tool.flet]
app_title = "Meshwar"

[tool.flet.app]
module = "meshwar"
exclude = [
    ".venv",
    ".git",
    ".github",
    "build",
    "__pycache__"
]